### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded. 

### ISSUE THREAD

**Issue by fessacchiotto** [Feuermurmel/youtube-podcast-gateway#13]
Hello. I'm getting this error (reported by google apis). How to fix it? Thank you!

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

Stack trace:

```
    uploads = self._gateway.service.get_channel_videos(channel.id, 'id', max_results = self._gateway.max_episode_count)         
  File "./lib/youtube.py", line 80, in get_channel_videos       
    return self._get(self._service.search(), part, channelId = channelId, order = order, type = 'video', max_results = max_results)                                                             
  File "./lib/youtube.py", line 97, in _get                     
    items = cls._get_raw(resource, part, max_results, **kwargs) 
  File "./lib/youtube.py", line 131, in _get_raw                
    response = request.execute()                                
  File "/home/ubuntu/youtube-podcast-gateway/venv/lib/python3.4/site-packages/oauth2client/util.py", line 137, in positional_wrapper                                                            
    return wrapped(*args, **kwargs)                             
  File "/home/ubuntu/youtube-podcast-gateway/venv/lib/python3.4/site-packages/googleapiclient/http.py", line 838, in execute    
    raise HttpError(resp, content, uri=self.uri)                
googleapiclient.errors.HttpError[236]: Handling request for /uploads/independentinstitute ...                                   
Requesting https://www.googleapis.com/youtube/v3/channels?part=snippet&id=independentinstitute&alt=json&maxResults=50 ...       
Traceback (most recent call last):                              
  File "./lib/gateway.py", line 230, in do_GET                  
    self._handle_feed_request(type, rest[0], audio_only)        
  File "./lib/gateway.py", line 273, in _handle_feed_request    
    feed = feed_type(id, audio_only)                            
  File "./lib/gateway.py", line 314, in _create_playlist_feed   
    title = playlist.snippet.title                              
AttributeError: 'NoneType' object has no attribute 'snippet'    
```

**Comment by Feuermurmel** [comment]
Did you follow the instructions to set up a Google Data API project and copy the `client_secrets.json` into the root of the project?

Otherwise, this may help: http://stackoverflow.com/a/25286631/402281
