### ISSUE TITLE
HttpError - OAUTH-related failure accessing playlists

### ISSUE THREAD

**Issue by lomacks** [Feuermurmel/youtube-podcast-gateway#25]
After working flawlessly for a couple of years, all requests to retrieve playlists have recently stopped working for me - possibly an OAUTH-related failure?

Reinstalling the virtualenv/dependencies, and redoing the API keys / oauth setup seem to have no effect.

Are you/anyone else seeing anything similar?

```
$ ./run.sh
Starting server on port 58181 ...
[1]: Handling request for /uploads/UC6cMYsKMx6XicFcFm7mTsmA ...
Requesting https://www.googleapis.com/youtube/v3/channels?alt=json&part=snippet&id=UC6cMYsKMx6XicFcFm7mTsmA&maxResults=50 ...
Traceback (most recent call last):
  File "./lib/gateway.py", line 230, in do_GET
    self._handle_feed_request(type, rest[0], audio_only)
  File "./lib/gateway.py", line 273, in _handle_feed_request
    feed = feed_type(id, audio_only)
  File "./lib/gateway.py", line 304, in _create_uploads_feed
    channel = self._gateway.service.get_channel_by_id_or_username(channel_id, 'snippet')
  File "./lib/youtube.py", line 54, in get_channel_by_id_or_username
    channel = self.get_channels(channel_id_or_username, part)
  File "./lib/youtube.py", line 72, in get_channels
    return self._get(self._service.channels(), part, id = channel_id)
  File "./lib/youtube.py", line 103, in _get
    items = self._get_raw(resource, part, id = id, **kwargs)
  File "./lib/youtube.py", line 132, in _get_raw
    response = request.execute()
  File "/opt/youtube-podcast-gateway/venv/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/youtube-podcast-gateway/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 844, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <exception str() failed>
```

(The same error repeats for every request)

**Comment by Feuermurmel** [comment]
Hmm … strange. I'm not seeing this issue and I'm not sure how I could reproduce it. :/ I would start by looking into what the actual error returned by the API is. For whatever reason it's not shown in the stack trace.
