### ISSUE TITLE
Some notes on how to successfully start the application...

### ISSUE THREAD

**Issue by erasmodanarni** [Feuermurmel/youtube-podcast-gateway#26]
First off, thank you for this great and very useful application.

After having installed from scratch:

1. it looks like you have to have at lest an option, for example: `-o max_episode_count=1000` otherwise it doesn't start

`Traceback (most recent call last):
  File "/home/yyy/venv/bin/youtube-podcast-gateway", line 11, in <module>
    load_entry_point('youtube-podcast-gateway==0.1', 'console_scripts', 'youtube-podcast-gateway')()
  File "/home/yyy/venv/lib/python3.6/site-packages/youtube_podcast_gateway/__init__.py", line 31, in entry_point
    main(**vars(parse_args()))
  File "/home/yyy/venv/lib/python3.6/site-packages/youtube_podcast_gateway/__init__.py", line 27, in main
    gateway.Gateway(config.Configuration(dict(options))).run()
TypeError: 'NoneType' object is not iterable`

2. you have to use the `canonical_base_url=http://example.com:8080`option otherwise, if you subscribe to a youtube channel or playlist with the port number, for example: `8080` , the file attached could not be retrieved because the port of subscription is added to the port of the file resources.

### Example of successful command line

`youtube-podcast-gateway -o max_episode_count=1000 -o canonical_base_url=http://example.com:8080`

**Comment by Feuermurmel** [comment]
Hey! Sorry for not getting back to you earlier.

Thank you for your investigation. This kind of documentation would definitely be a good addition to the project.

Sadly, I haven't been using this project myself for multiple years now and thus can't investigate any issues or test fixes. If someone else wants to take it over, I'll gladly transfer it.
