### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by rucomcode** [Feuermurmel/youtube-podcast-gateway#29]
```
[4]: Handling request for /playlist/PLV9o5alTk7g1-q8dPcwwPj94hW2MVcAME ...
Requesting https://www.googleapis.com/youtube/v3/playlists?part=snippet&maxResults=50&id=PLV9o5alTk7g1-q8dPcwwPj94hW2MVcAME&alt=json ...
Traceback (most recent call last):
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/gateway.py", line 268, in do_GET
    self._handle_feed_request(type, id, audio_only)
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/gateway.py", line 323, in _handle_feed_request
    feed = feed_type(id, audio_only)
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/gateway.py", line 368, in _create_playlist_feed
    playlist = self._gateway.service.get_playlists(playlist_id, 'snippet')
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/youtube.py", line 89, in get_playlists
    return self._get(self._service.playlists(), part, id=playlist_id)
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/youtube.py", line 137, in _get
    items = self._get_raw(resource, part, id=id, **kwargs)
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/youtube_podcast_gateway/youtube.py", line 166, in _get_raw
    response = request.execute()
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/roman/youtube/venv/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <exception str() failed>
```

**Comment by Feuermurmel** [comment]
Hey! Sorry for not getting back to you earlier, I hope you have moved on though 😉.

Nonetheless, I haven't been using this project myself for multiple years now and thus can't investigate any issues or test fixes. If someone else wants to take it over, I'll gladly transfer it.

**Comment by Feuermurmel** [comment]
Hey! Sorry for not getting back to you earlier, I hope you have moved on though 😉.

Nonetheless, I haven't been using this project myself for multiple years now and thus can't investigate any issues or test fixes. If someone else wants to take it over, I'll gladly transfer it.
