### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by erasmodanarni** [Feuermurmel/youtube-podcast-gateway#30]
Hello! I'm getting the following error, after a fresh install, when I request a file through the Apple IOS stock podcast app:

`[3]: Handling request for /video/Y0budGEwSYY.m4v ...
[3]: Request for range bytes=0-1 of video Y0budGEwSYY.
Getting URL for video Y0budGEwSYY ...
Traceback (most recent call last):
  File "/home/maurizio/podcast/venv/lib/python3.7/site-packages/youtube_podcast_gateway/gateway.py", line 264, in do_GET
    self._gateway.file_factory.get_file(id, False))
  File "/home/maurizio/podcast/venv/lib/python3.7/site-packages/youtube_podcast_gateway/gateway.py", line 343, in _handle_media_request
    request = urllib.request.Request(file.download_url)
  File "/home/maurizio/podcast/venv/lib/python3.7/site-packages/youtube_podcast_gateway/gateway.py", line 100, in download_url
    self._download_url = self._get_download_url()
  File "/home/maurizio/podcast/venv/lib/python3.7/site-packages/youtube_podcast_gateway/gateway.py", line 66, in _get_download_url
    url = self._get_url_for_format(i)
  File "/home/maurizio/podcast/venv/lib/python3.7/site-packages/youtube_podcast_gateway/gateway.py", line 91, in _get_url_for_format
    'Getting the download URL failed: {}'.format(message))
Exception: Getting the download URL failed: ERROR: Signature extraction failed: Traceback (most recent call last):
`

The server is installed on Ubuntu Bionic Beaver (18.04 LTS). Python 3.7.3.
 
Any ideas on how to fix it? Thanks!

**Comment by Feuermurmel** [comment]
Hey! Sorry for not getting back to you earlier, I hope you have moved on though 😉.

Nonetheless, I haven't been using this project myself for multiple years now and thus can't investigate any issues or test fixes. If someone else wants to take it over, I'll gladly transfer it.
