### ISSUE TITLE
Issues with channels with hundreds of videos

### ISSUE THREAD

**Issue by agizmo** [Feuermurmel/youtube-podcast-gateway#4]
I was trying to generate a RSS feed of uploads from the RoosterTeeth channel and ran into issues. It looks like the application was pulling multiple, 50 results pages and eventually things broke. Is there a way to limit things to just 50 results and not have multiple pages?

I saw in youtube.py there is `_max_results = 50`, but that appears to limit the number of results per page. If I change the setting to something like 15, multiple pages are still requested.

URL: http://localhost:8080/uploads/UCzH3iADRIq1IJlIXjfNgTpA

```
tony@ubuntuv2:~/yt5/youtube-podcast-gateway-master$ ./run.sh 
Starting server on port 8080 ...
[1]: Handling request for /uploads/UCzH3iADRIq1IJlIXjfNgTpA ...
Requesting https://www.googleapis.com/youtube/v3/channels?alt=json&maxResults=50&part=contentDetails%2Csnippet&id=UCzH3iADRIq1IJlIXjfNgTpA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CDIQAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CGQQAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJYBEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMgBEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPoBEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKwCEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CN4CEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJADEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMIDEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPQDEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKYEEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNgEEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIoFEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLwFEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CO4FEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKAGEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNIGEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIQHEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLYHEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COgHEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJoIEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMwIEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CP4IEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLAJEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COIJEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJQKEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMYKEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPgKEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKoLEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNwLEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CI4MEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMAMEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPIMEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKQNEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNYNEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIgOEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLoOEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COwOEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJ4PEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNAPEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIIQEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLQQEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COYQEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJgREAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMoREAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPwREAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CK4SEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COASEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJITEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMQTEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPYTEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKgUEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNoUEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIwVEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CL4VEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPAVEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKIWEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNQWEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIYXEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLgXEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COoXEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJwYEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CM4YEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIAZEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLIZEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COQZEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJYaEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMgaEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPoaEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKwbEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CN4bEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJAcEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMIcEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CPQcEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKYdEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNgdEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIoeEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLweEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CO4eEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CKAfEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CNIfEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CIQgEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CLYgEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=COggEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CJohEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CMwhEAA ...
Requesting https://www.googleapis.com/youtube/v3/playlistItems?maxResults=50&playlistId=UUzH3iADRIq1IJlIXjfNgTpA&part=contentDetails&alt=json&pageToken=CP4hEAA ...
Traceback (most recent call last):
  File "./lib/gateway.py", line 230, in _handle_request
    self._handle_feed_request(handler, type, rest[0], audio_only)
  File "./lib/gateway.py", line 267, in _handle_feed_request
    feed = feed_type(id, audio_only)
  File "./lib/gateway.py", line 299, in _create_uploads_feed
    playlist_items = self._gateway.service.get_playlist_items(channel.contentDetails.relatedPlaylists.uploads, 'contentDetails')
  File "./lib/youtube.py", line 77, in get_playlist_items
    return self._get(self._service.playlistItems(), part = part, playlistId = playlist_id)
  File "./lib/youtube.py", line 92, in _get
    items = cls._get_raw(resource, part, **kwargs)
  File "./lib/youtube.py", line 126, in _get_raw
    return [_Item.wrap_json(i) for i in iter_items()]
  File "./lib/youtube.py", line 126, in <listcomp>
    return [_Item.wrap_json(i) for i in iter_items()]
  File "./lib/youtube.py", line 120, in iter_items
    response = request.execute()
  File "/home/tony/yt5/youtube-podcast-gateway-master/venv/lib/python3.4/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/tony/yt5/youtube-podcast-gateway-master/venv/lib/python3.4/site-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)

```

I am running this on a Ubuntu 14.04 x64 virtual machine with 2GB of memory (this is a test system before I move it to a larger home server). Here is the output from installing.

``````
tony@ubuntuv2:~/yt5/youtube-podcast-gateway-master$ ls
client_secrets.json  lib  __main__.py  oauth2_token.json  run.sh  setup-venv.sh
tony@ubuntuv2:~/yt5/youtube-podcast-gateway-master$ ./setup-venv.sh 
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in venv/bin/python3.4
Also creating executable in venv/bin/python
Installing setuptools, pip...done.
Downloading/unpacking google-api-python-client
  Downloading google-api-python-client-1.4.0.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/google-api-python-client/setup.py) egg_info for package google-api-python-client

    warning: no files found matching '*.json' under directory 'apiclient'
    warning: no files found matching 'README'
    warning: no files found matching 'FAQ'
    warning: no files found matching 'setpath.sh'
Downloading/unpacking isodate
  Downloading isodate-0.5.1.tar.gz
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/isodate/setup.py) egg_info for package isodate

Downloading/unpacking pytz
  Downloading pytz-2015.2-py2.py3-none-any.whl (476kB): 476kB downloaded
Downloading/unpacking httplib2>=0.8 (from google-api-python-client)
  Downloading httplib2-0.9.1.tar.gz (205kB): 205kB downloaded
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/httplib2/setup.py) egg_info for package httplib2

Downloading/unpacking oauth2client>=1.4.6 (from google-api-python-client)
  Downloading oauth2client-1.4.7.tar.gz (48kB): 48kB downloaded
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/oauth2client/setup.py) egg_info for package oauth2client

Downloading/unpacking six>=1.6.1 (from google-api-python-client)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking uritemplate>=0.6 (from google-api-python-client)
  Downloading uritemplate-0.6.tar.gz
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/uritemplate/setup.py) egg_info for package uritemplate

Downloading/unpacking pyasn1==0.1.7 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading pyasn1-0.1.7.tar.gz (68kB): 68kB downloaded
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/pyasn1/setup.py) egg_info for package pyasn1

Downloading/unpacking pyasn1-modules==0.0.5 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading pyasn1-modules-0.0.5.tar.gz
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/pyasn1-modules/setup.py) egg_info for package pyasn1-modules

Downloading/unpacking rsa==3.1.4 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading rsa-3.1.4.tar.gz
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/rsa/setup.py) egg_info for package rsa

    warning: no files found matching 'README'
Downloading/unpacking simplejson>=2.5.0 (from uritemplate>=0.6->google-api-python-client)
  Downloading simplejson-3.6.5.tar.gz (73kB): 73kB downloaded
  Running setup.py (path:/home/tony/yt5/youtube-podcast-gateway-master/venv/build/simplejson/setup.py) egg_info for package simplejson

Installing collected packages: google-api-python-client, isodate, pytz, httplib2, oauth2client, six, uritemplate, pyasn1, pyasn1-modules, rsa, simplejson
  Running setup.py install for google-api-python-client

    warning: no files found matching '*.json' under directory 'apiclient'
    warning: no files found matching 'README'
    warning: no files found matching 'FAQ'
    warning: no files found matching 'setpath.sh'
  Running setup.py install for isodate
    Fixing build/lib/isodate/__init__.py build/lib/isodate/isodates.py build/lib/isodate/isotime.py build/lib/isodate/duration.py build/lib/isodate/isotzinfo.py build/lib/isodate/tzinfo.py build/lib/isodate/isoerror.py build/lib/isodate/isoduration.py build/lib/isodate/isodatetime.py build/lib/isodate/isostrf.py build/lib/isodate/tests/test_date.py build/lib/isodate/tests/test_duration.py build/lib/isodate/tests/__init__.py build/lib/isodate/tests/test_pickle.py build/lib/isodate/tests/test_time.py build/lib/isodate/tests/test_strf.py build/lib/isodate/tests/test_datetime.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    Fixing build/lib/isodate/__init__.py build/lib/isodate/isodates.py build/lib/isodate/isotime.py build/lib/isodate/duration.py build/lib/isodate/isotzinfo.py build/lib/isodate/tzinfo.py build/lib/isodate/isoerror.py build/lib/isodate/isoduration.py build/lib/isodate/isodatetime.py build/lib/isodate/isostrf.py build/lib/isodate/tests/test_date.py build/lib/isodate/tests/test_duration.py build/lib/isodate/tests/__init__.py build/lib/isodate/tests/test_pickle.py build/lib/isodate/tests/test_time.py build/lib/isodate/tests/test_strf.py build/lib/isodate/tests/test_datetime.py
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma

  Running setup.py install for httplib2

  Running setup.py install for oauth2client

  Running setup.py install for uritemplate

  Running setup.py install for pyasn1

  Running setup.py install for pyasn1-modules

  Running setup.py install for rsa

    warning: no files found matching 'README'
    Installing pyrsa-keygen script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-priv2pub script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-decrypt-bigfile script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-sign script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-encrypt script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-decrypt script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-verify script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
    Installing pyrsa-encrypt-bigfile script to /home/tony/yt5/youtube-podcast-gateway-master/venv/bin
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/tony/yt5/youtube-podcast-gateway-master/venv/include/python3.4m -c simplejson/_speedups.c -o build/temp.linux-x86_64-3.4/simplejson/_speedups.o
    simplejson/_speedups.c:2:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    ***************************************************************************
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    I'm retrying the build without the C extension now.
    ***************************************************************************

    ***************************************************************************
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ***************************************************************************
Successfully installed google-api-python-client isodate pytz httplib2 oauth2client six uritemplate pyasn1 pyasn1-modules rsa simplejson
Cleaning up...```
``````

**Comment by Feuermurmel** [comment]
I tried subscribing using the URL you provided and it did work for me. Is it possible that the last line of your first output listing, containing the exception message, was cut off? I can't see what was causing the exception.

OTOH, I can definitely see the need to limit the number of episodes of a returned feed. The channel you mentioned has 6468 videos, resulting in about 260 requests that need to be made against the YouTube API (YouTube limits requests to 50 videos per batch and there are 2 requests necessary for each batch). None of the clients I tested was willing to wait that long and eventually reported a timeout. I will add an option to limit the number of episodes in a feed to the newest N videos.

**Comment by Feuermurmel** [comment]
@agizmo I've implemented a setting for the maximum number of episodes to be retrieved: https://github.com/Feuermurmel/youtube-podcast-gateway/tree/limit-episode-count (see _Configuration_ in the readme). Can you try whether this solves your issues?

**Comment by agizmo** [comment]
The new feature is working like a charm. Had no issues loading the RoosterTeeth podcast with the count set to 20.

Yesterday morning I tried loading the RosterTeeth podcast after you replied and was able to fully load it without issue (other than it took a few minutes to pull all the pages). Don't know why it didn't work Tuesday evening, but did Wednesday morning.

**Comment by Feuermurmel** [comment]
Very glad to hear that! :)

I'm closing this issue as I can't debug the original problem. The error message was truncated because of a bug in `googleapiclient` for which I've since added a workaround.
