### ISSUE TITLE
Remove upcoming live events form feed

### ISSUE THREAD

**Issue by Feuermurmel** [Feuermurmel/youtube-podcast-gateway#8]
Output when requesting a video which is actually an upcoming live event.

```
[77]: Request for range None of video lqsN_4wXuRg.
Getting URL for video lqsN_4wXuRg ...
Traceback (most recent call last):
  File "./lib/gateway.py", line 226, in do_GET
    self._handle_media_request(self._gateway.file_factory.get_file(rest[0], False))
  File "./lib/gateway.py", line 288, in _handle_media_request
    request = urllib.request.Request(file.download_url)
  File "./lib/gateway.py", line 81, in download_url
    self._download_url = self._get_download_url()
  File "./lib/gateway.py", line 54, in _get_download_url
    url = self._get_url_for_format(i)
  File "./lib/gateway.py", line 72, in _get_url_for_format
    'Getting the download URL failed: {}'.format(message))
Exception: Getting the download URL failed: ERROR: uefD6LUhyUE: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "./lib/gateway.py", line 226, in do_GET
    self._handle_media_request(self._gateway.file_factory.get_file(rest[0], False))
  File "./lib/gateway.py", line 288, in _handle_media_request
    request = urllib.request.Request(file.download_url)
  File "./lib/gateway.py", line 81, in download_url
    self._download_url = self._get_download_url()
  File "./lib/gateway.py", line 54, in _get_download_url
    url = self._get_url_for_format(i)
  File "./lib/gateway.py", line 72, in _get_url_for_format
    'Getting the download URL failed: {}'.format(message))
Exception: Getting the download URL failed: ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Feuermurmel** [comment]
Output when requesting a video which is actually an upcoming live event.

```
[77]: Request for range None of video lqsN_4wXuRg.
Getting URL for video lqsN_4wXuRg ...
Traceback (most recent call last):
  File "./lib/gateway.py", line 226, in do_GET
    self._handle_media_request(self._gateway.file_factory.get_file(rest[0], False))
  File "./lib/gateway.py", line 288, in _handle_media_request
    request = urllib.request.Request(file.download_url)
  File "./lib/gateway.py", line 81, in download_url
    self._download_url = self._get_download_url()
  File "./lib/gateway.py", line 54, in _get_download_url
    url = self._get_url_for_format(i)
  File "./lib/gateway.py", line 72, in _get_url_for_format
    'Getting the download URL failed: {}'.format(message))
Exception: Getting the download URL failed: ERROR: uefD6LUhyUE: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "./lib/gateway.py", line 226, in do_GET
    self._handle_media_request(self._gateway.file_factory.get_file(rest[0], False))
  File "./lib/gateway.py", line 288, in _handle_media_request
    request = urllib.request.Request(file.download_url)
  File "./lib/gateway.py", line 81, in download_url
    self._download_url = self._get_download_url()
  File "./lib/gateway.py", line 54, in _get_download_url
    url = self._get_url_for_format(i)
  File "./lib/gateway.py", line 72, in _get_url_for_format
    'Getting the download URL failed: {}'.format(message))
Exception: Getting the download URL failed: ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by fessacchiotto** [comment]
Thank you for writing this software! :)
